name: Docker Build

on:
  push:
    branches-ignore:
      - master

jobs:
  container-build-feature:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: make build
    - name: Test Docker image
      run: make test
